[package]
# 확장 프로그램의 버전과 정보를 입력합니다.
version = "1.0.0"
title = "Dongjae G1 Study Extension"
description = "Custom G1 loading example for study"
authors = ["Dongjae"]
repository = ""
keywords = ["isaac", "g1", "study"]
changelog = ""
readme = ""
preview_image = ""
icon = ""

# 이 확장 프로그램이 의존하는 다른 모듈들입니다.
[dependencies]
"isaacsim.examples.browser" = {}
"isaacsim.examples.interactive" = {}
"isaacsim.core.api" = {}

# [중요] 실행할 메인 파이썬 모듈을 지정합니다.
# [deploy/extension.toml]의 맨 아랫부분 수정
[[python.module]]
name = "loco_extension"

[[python.module]]
name = "catch_extension"

[[python.module]]
name = "merged_extension"

[[python.module]]
name = "practice_extension"
